# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190828_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
